# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    
  end

lane :to_firim do

  sh “git reset —-hard”
  sh "git checkout master”

  # 如果你用 pod install
  cocoapods

  # 如果你没有申请adhoc证书，sigh会自动帮你申请，并且添加到Xcode里
  sigh(adhoc: true)
  # 以下两个action来自fastlane-plugin-versioning，
  # 第一个递增 Build，第二个设定Version。
  # 如果你有多个target，就必须指定target的值，否则它会直接找找到的第一个plist修改
  # 在这里我建议每一个打的包的Build都要不一样，这样crash了拿到日志，可以对应到ipa上
  #increment_build_number_in_plist(target: [target_name])
  #increment_version_number_in_plist(
  #  target: [target_name],
  #  version_number: '7.1.3'
  #  )

  increment_build_number
  git_increase_build_version(branch: "master")
  # gym用来编译ipa
  gym(
    clean: true,
    scheme: “store”,
    output_directory: ‘/Users/wangshuaifeng/Desktop/firim'
    )
  # 上传ipa到fir.im服务器，在fir.im获取firim_api_token
  firim(firim_api_token: “150fc05a8dad7688751005a75f07c06d”)
  
end

lane :to_appstore do
  sh “git reset —-hard”
  sh "git checkout master”

  # 如果你用 pod install
  cocoapods
  # 执行 pod instasll
  #cocoapods
  # 执行 carthage bootstrap
  # carthage
  # 增加build版本号
  increment_build_number
  git_increase_build_version(branch: "master")
  # 编译代码

   #increment_build_number_in_plist(target: “individual”)
   #increment_version_number_in_plist(
   # target: “individual”,
   # version_number: ‘1.0.3’
   # )
  gym(
	clean: true,
	scheme: “store”,
	configuration: ”Release”
	)
  # 发布到Apple Store
  deliver(
	   force: true,
	   submit_for_review: true,
	   submission_information: {add_id_info_serves_ads: false}
	)
end


  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "store") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "store") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
