platform :ios, '8.0'
target 'store' do
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'YYText'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'
pod 'UITableView+FDTemplateLayoutCell'
pod 'EAIntroView', '~> 2.10.0'
end
